# Generated by Django 3.0.6 on 2020-05-30 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig', models.CharField(max_length=512)),
                ('short', models.CharField(max_length=5, unique=True)),
                ('extra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.BigIntegerField()),
                ('date', models.DateTimeField(verbose_name='Get request time')),
                ('long', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('agent', models.CharField(max_length=128)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutter.Link', to_field='short')),
            ],
        ),
    ]
