# Generated by Django 3.0.6 on 2020-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0002_auto_20200530_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stats',
            name='long',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
